import { Component, OnDestroy, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';

interface Ticket { id: number; name: string; created_at: string; started_at?: string; status?: string; table_id?: number | null }
interface Station { id: number; ticket: Ticket | null }
interface State { tables: Station[]; queue: Ticket[]; current: Station | null; next_number: number }

@Component({ selector: 'app-root', standalone: true, imports: [CommonModule, FormsModule], template: `
<header class="topbar"><div class="brand"><span class="mark">A</span><span>Atención<small>Sistema de turnos</small></span></div><div class="right"><span class="live">Sistema activo</span><button class="outline" (click)="reset()">Reiniciar jornada</button></div></header>
<main class="wrap" *ngIf="!isDisplay"><div class="intro"><div><div class="eyebrow">Panel de atención</div><h1>Gestión de turnos</h1><p>Los turnos avanzan automáticamente al liberarse una mesa.</p></div><div class="date">{{ today | date:'EEEE, d MMMM y':'':'es-MX' }}</div></div>
<div class="layout"><div><section class="card"><div class="cardhead"><div><h2>Mesas de atención</h2><p>Cuatro estaciones de servicio</p></div><span class="pill">{{ occupied }} / 4 ocupadas</span></div><div class="stations"><article class="station" *ngFor="let t of state.tables" [class.busy]="!!t.ticket"><div class="stationhead"><strong>Mesa {{t.id}}</strong><span class="status">{{t.ticket ? 'Atendiendo' : 'Disponible'}}</span></div><ng-container *ngIf="t.ticket; else free"><div class="turn">{{fmt(t.ticket.id)}}</div><div class="caption">{{t.ticket.name || 'Cliente'}} · Turno llamado</div><button class="finish" (click)="finish(t.id)">Finalizar atención</button></ng-container><ng-template #free><div class="free">Lista para atender</div></ng-template></article></div></section>
<section class="card queue"><div class="cardhead"><div><h2>Turnos en espera</h2><p>Se atienden en orden de llegada</p></div><span class="pill">{{state.queue.length}} en fila</span></div><div class="queuebody" *ngIf="state.queue.length; else noQueue"><div class="qrow" *ngFor="let q of state.queue.slice(0,8);let i=index"><strong>{{fmt(q.id)}}</strong><span>{{q.name || 'Cliente'}} <em *ngIf="i===0">· siguiente</em></span><small>{{q.created_at | date:'shortTime'}}</small></div><p class="muted" *ngIf="state.queue.length>8">Y {{state.queue.length-8}} turno(s) más...</p></div><ng-template #noQueue><div class="queuebody muted">No hay clientes esperando.</div></ng-template></section></div>
<aside><section class="card formcard"><h2>Dar turno</h2><p>Registra al cliente para agregarlo a la fila.</p><label for="name">Nombre del cliente <small>(opcional)</small></label><input id="name" [(ngModel)]="name" (keydown.enter)="create()" maxlength="60" placeholder="Ej. María López"><button class="primary" (click)="create()">+ Asignar siguiente turno</button><div class="receipt" *ngIf="receipt"><small>Turno asignado</small><strong>{{fmt(receipt.id)}}</strong><p>{{receipt.name || 'Cliente'}} · {{receipt.status === 'in_service' ? 'Pasa a Mesa '+receipt.table_id : 'En espera · '+state.queue.length+' en fila'}}</p></div></section>
<section class="display"><div class="displayhead"><strong>Pantalla de llamados</strong><small>Vista para clientes</small></div><div class="displaygrid"><div><small>Atendiendo ahora</small><strong>{{state.current ? 'Turno '+fmt(state.current.ticket!.id) : '—'}}</strong><span>{{state.current ? 'Pase a Mesa '+state.current.id : 'Esperando turno'}}</span></div><div class="next"><small>Próximo en espera</small><strong>{{state.queue.length ? 'Turno '+fmt(state.queue[0].id) : '—'}}</strong><span>{{state.queue.length ? 'Próximo en la fila' : 'Sin turnos pendientes'}}</span></div></div></section><div class="actions"><button class="outline" (click)="sound=!sound">{{sound?'🔔 Sonido activado':'🔕 Sonido desactivado'}}</button><button class="outline" (click)="fullscreen()">⛶ Pantalla completa</button></div><p class="hint">Los datos se guardan en la base local del servidor.</p></aside></div></main>
<main class="public" *ngIf="isDisplay"><div class="pubbrand">ATENCIÓN · LLAMADO DE TURNO</div><h1>Turno actual</h1><div class="hero" *ngIf="state.current; else nobody"><strong>{{fmt(state.current.ticket!.id)}}</strong><span>Pase a</span><b>Mesa {{state.current.id}}</b></div><ng-template #nobody><div class="hero empty"><strong>—</strong><b>En un momento le atenderemos</b></div></ng-template><h2>Próximos turnos</h2><div class="upcoming"><span *ngFor="let q of state.queue.slice(0,4)">{{fmt(q.id)}}</span><span *ngIf="!state.queue.length" class="muted">Sin turnos en espera</span></div></main>
`, styleUrl: './app.component.css' })
export class AppComponent implements OnInit, OnDestroy {
  private http = inject(HttpClient); private socket?: WebSocket; private timer?: number;
  state: State = { tables: [1,2,3,4].map(id => ({id,ticket:null})), queue: [], current:null, next_number:1 };
  name=''; sound=true; receipt: {id:number; name:string; status:string; table_id:number|null}|null=null; today=new Date();
  isDisplay = location.pathname === '/display';
  get occupied(): number { return this.state.tables.filter(t => !!t.ticket).length; }
  ngOnInit(): void { this.http.get<State>('/api/state').subscribe(s => this.state=s); this.connect(); }
  ngOnDestroy(): void { this.socket?.close(); if(this.timer) window.clearTimeout(this.timer); }
  connect(): void { const protocol=location.protocol==='https:'?'wss':'ws'; this.socket=new WebSocket(`${protocol}://${location.hostname}:8000/ws`); this.socket.onmessage=e=>this.state=JSON.parse(e.data) as State; this.socket.onclose=()=>{this.timer=window.setTimeout(()=>this.connect(),2000);}; }
  fmt(n:number):string { return String(n).padStart(2,'0'); }
  create(): void { this.http.post<typeof this.receipt>('/api/tickets',{name:this.name.trim()}).subscribe(r=>{this.receipt=r;this.name='';if(this.sound&&r?.status==='in_service')this.beep();}); }
  finish(id:number): void { this.http.post<State>(`/api/tables/${id}/finish`,{}).subscribe(s=>this.state=s); }
  reset(): void { if(confirm('¿Reiniciar la jornada? Se borrarán los turnos y la numeración empezará de nuevo.'))this.http.post<State>('/api/reset',{}).subscribe(s=>{this.state=s;this.receipt=null;}); }
  fullscreen(): void { if(!document.fullscreenElement) void document.documentElement.requestFullscreen?.(); else void document.exitFullscreen?.(); }
  beep(): void { try { const c=new AudioContext(); [0,.17].forEach((t,i)=>{const o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=i?880:660;g.gain.setValueAtTime(.001,c.currentTime+t);g.gain.exponentialRampToValueAtTime(.13,c.currentTime+t+.02);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+t+.13);o.start(c.currentTime+t);o.stop(c.currentTime+t+.14);});window.setTimeout(()=>void c.close(),600); } catch {} }
}
